version: "3.9"


services: 

    db:
        container_name: feedbacks_db
        image: postgres 
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSGRES_DB=${DB_NAME}

    pgadmin:

        container_name: pgadmin
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}  
        ports: 
            - 5000:80
        
    app:
        container_name: app
        build: .
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload" 
        volumes: 
            - .:/app
        ports: 
            - 8000:8000
        restart: always
