"""New Migration

Revision ID: 63616fd78d05
Revises: 
Create Date: 2021-08-05 12:53:32.686468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63616fd78d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
